### ISSUE TITLE
Expected '<component>' elements to have 'v-bind:is' attribute  vue/require-component-is

### ISSUE THREAD

**Issue by matamune94** [nuxt/eslint-plugin-nuxt#73] opened 2019-11-26 03:00 UTC
maybe update something for fix this error ?
they say use eslint-plugin-vue@6 
https://github.com/vuejs/eslint-plugin-vue/issues/869#issuecomment-553673273

**Comment by manniL** [comment] 2019-11-26 09:08
Duplicate of https://github.com/nuxt/eslint-plugin-nuxt/issues/65

**Closed by manniL** 2019-11-26 09:08 UTC
